// Generated by `npm run refresh:category-artwork`. Do not edit manually.
export const categoryArtworkVersions = {
  "bottoms": {"version":"89148700ae694124","width":396,"height":594,"displayScale":1.02,"hoverScale":1.07},
  "crop-tops": {"version":"e75a74a118985bc3","width":445,"height":560,"displayScale":1.02,"hoverScale":1.07},
  "denim-jackets": {"version":"9917f0c8432c6748","width":445,"height":560,"displayScale":1.02,"hoverScale":1.07},
  "dress": {"version":"ea34242a8a4a6216","width":408,"height":612,"displayScale":1.02,"hoverScale":1.07},
  "hoodie": {"version":"16d7e077a37c9936","width":408,"height":612,"displayScale":1.02,"hoverScale":1.07},
  "jackets": {"version":"bc4940a5a236499d","width":408,"height":612,"displayScale":1.02,"hoverScale":1.07},
  "shirt": {"version":"601476d4aaf82b97","width":408,"height":612,"displayScale":1.02,"hoverScale":1.07},
  "shrug": {"version":"5ae24facc90d251c","width":489,"height":510,"displayScale":1.02,"hoverScale":1.07},
  "tops": {"version":"d79ab0bbaed92533","width":447,"height":558,"displayScale":1.02,"hoverScale":1.07},
  "sweater": {"version":"4e3e42ff962f343d","width":445,"height":560,"displayScale":1.02,"hoverScale":1.07},
  "sweatshirt": {"version":"8238e84e66076efb","width":408,"height":612,"displayScale":1.02,"hoverScale":1.07},
  "t-shirt": {"version":"4a130fa1daf1de3b","width":408,"height":612,"displayScale":1.02,"hoverScale":1.07},
} as const;
