import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const categoryAssetsDirectory = path.join(process.cwd(), 'app', 'design-lab', 'category-assets');
const outputFile = path.join(process.cwd(), 'lib', 'design-lab', 'category-artwork-versions.ts');
const assetToCategoryPath: Record<string, string> = { 'sweater-alt': 'tops' };
const ignoredAssets = new Set(['tops.png']);

async function main() {
  const files = (await readdir(categoryAssetsDirectory))
    .filter((file) => /\.(png|jpe?g|webp)$/i.test(file) && !ignoredAssets.has(file))
    .sort((left, right) => left.localeCompare(right));

  const artwork = await Promise.all(files.map(async (file) => {
    const contents = await readFile(path.join(categoryAssetsDirectory, file));
    const metadata = await sharp(contents, { failOn: 'error' }).metadata();
    if (!metadata.width || !metadata.height) throw new Error(`Could not read dimensions for ${file}`);
    const fileStem = file.replace(/\.(png|jpe?g|webp)$/i, '');
    const categoryPath = assetToCategoryPath[fileStem] ?? fileStem;
    // Portrait garments need a slightly smaller increase so their complete silhouette remains visible.
    const displayScale = metadata.height > metadata.width ? 1.02 : 1.13;
    const hoverScale = metadata.height > metadata.width ? 1.07 : 1.17;

    return [categoryPath, {
      version: createHash('sha256').update(contents).digest('hex').slice(0, 16),
      width: metadata.width,
      height: metadata.height,
      displayScale,
      hoverScale,
    }] as const;
  }));

  const source = [
    '// Generated by `npm run refresh:category-artwork`. Do not edit manually.',
    'export const categoryArtworkVersions = {',
    ...artwork.map(([categoryPath, details]) => `  ${JSON.stringify(categoryPath)}: ${JSON.stringify(details)},`),
    '} as const;',
    '',
  ].join('\n');

  await writeFile(outputFile, source, 'utf8');
  console.log(`Refreshed ${artwork.length} protected category-artwork version(s), including native image dimensions.`);
}

void main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});